from landslide_model.Unet import UNet
from landslide_model.UnetPP import UNet_Nested
from landslide_model.Segformer import SegFormer
from landslide_model.MFFEnet import DeepLab  
from landslide_model.RIPF_Unet import RiPF_UNet  
from landslide_model.transUnet2 import TransUNet2  
from landslide_model.attention_deeplabv3plus import AttentionDeeplabV3plus  
from landslide_model.BFA_ResUnet import BFA_resunet 
from landslide_model.DC_light import *
